### PR TITLE
Added new docs from sheep, fixed dead links, removed old images and assets.

### PR DESCRIPTION
**Pull request by what-does-that-do**
This fixes **all** issues raised about the docs site.

### CODE REVIEW

**Comment by what-does-that-do** [comment]
Please could someone give this a quick check (see preview under `show all checks -> Cloudflare details -> Go to preview URL` )? Should fix all the issues!

**Comment by MostlyTurquoise** [comment]
There are some content / clarification changes that could be made but those are for future pull requests! This looks good - or at least a lot better than whats currently up.

**Comment by MostlyTurquoise** [comment]
ok I can't find the review approve button on github mobile, remind me tomorrow and ill do it when im back on my laptop.

**Comment by what-does-that-do** [comment]
Ok cool - yeah I'm aware of the future improvements needed to the docs in terms of content. 

I am planning to re-write some of the challenges and general docs guides to make them clearer in future, as I saw how some of the docs can be misinterpreted at a mentoring session! 

But right now the priority is just to merge the current changes in from sheep and fix dead images 😀

**Review by MostlyTurquoise — APPROVED** [review]

**Pull request merged**
